# Generated by Django 4.2.7 on 2023-12-18 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_language_book_language'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='volume',
            field=models.IntegerField(null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='book',
            name='ibsn',
            field=models.CharField(help_text='13 Characters <a href="https://www.isbn-international.org/content/what-isbn">ISBN number</a>', max_length=13, unique=True, verbose_name='IBSN'),
        ),
    ]
