# Generated by Django 4.2.7 on 2023-12-18 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_book_volume_alter_book_ibsn'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='volume',
            field=models.IntegerField(null=True),
        ),
    ]
